// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TvServer.Models;

#nullable disable

namespace TvServerV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250805021548_addToken")]
    partial class addToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TvServer.Models.Roku.HardwareModels.RokuApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RokuAppsId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RokuAppsId");

                    b.ToTable("RokuApp");
                });

            modelBuilder.Entity("TvServer.Models.Roku.HardwareModels.RokuApps", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RokuApps");
                });

            modelBuilder.Entity("TvServer.Models.Roku.HardwareModels.RokuDeviceInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AdvertisingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvSyncCalibrationEnabled")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClockFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultDeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DeveloperEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("DeviceAutomationBridgeEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EthernetMac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ExpertPqEnabled")
                        .HasColumnType("real");

                    b.Property<string>("FriendlyDeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FriendlyModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrandcentralVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasHandsFreeVoiceRemote")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMobileScreensaver")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPlayOnRoku")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWifi5GSupport")
                        .HasColumnType("boolean");

                    b.Property<bool>("HeadphonesConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStick")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTv")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyedDeveloperId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightningBaseBuildNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MobileHasLiveTv")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NetworkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PanelId")
                        .HasColumnType("integer");

                    b.Property<string>("PowerMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScreenSize")
                        .HasColumnType("integer");

                    b.Property<bool>("SearchChannelsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SearchEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SecureDevice")
                        .HasColumnType("boolean");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoftwareBuild")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupportUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SupportsAirplay")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsAudioGuide")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsAudioSettings")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsEcsMicrophone")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsEcsTextedit")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsEthernet")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsFindRemote")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsPrivateListening")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsPrivateListeningDtv")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsRva")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsSuspend")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTrc")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsWakeOnWlan")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsWarmStandby")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TimeZoneAuto")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZoneName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeZoneOffset")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneTz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrcChannelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrcVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TunerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Udn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UiBuildNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UiResolution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UiSoftwareBuild")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UiSoftwareVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Uptime")
                        .HasColumnType("integer");

                    b.Property<string>("UserDeviceLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserDeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("VoiceSearchEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("WifiDriver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WifiMac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RokuDeviceInfo");
                });

            modelBuilder.Entity("TvServer.Models.Roku.SavedRokuDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DeviceInfoId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastKnownIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RokuAppsId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceInfoId");

                    b.HasIndex("RokuAppsId");

                    b.ToTable("RokuDevices");
                });

            modelBuilder.Entity("TvServer.Models.Samsung.Events.SamsungAppData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AppType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsLock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SavedSamsungDeviceEntityId")
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("SavedSamsungDeviceEntityId");

                    b.ToTable("SamsungAppData");
                });

            modelBuilder.Entity("TvServer.Models.Samsung.HardwareModels.SamsungAdditionalDeviceInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeveloperIP")
                        .HasColumnType("text");

                    b.Property<string>("DeveloperMode")
                        .HasColumnType("text");

                    b.Property<string>("Duid")
                        .HasColumnType("text");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text");

                    b.Property<string>("FrameTVSupport")
                        .HasColumnType("text");

                    b.Property<string>("GamePadSupport")
                        .HasColumnType("text");

                    b.Property<string>("ImeSyncedSupport")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NetworkType")
                        .HasColumnType("text");

                    b.Property<string>("OS")
                        .HasColumnType("text");

                    b.Property<string>("PowerState")
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("SmartHubAgreement")
                        .HasColumnType("text");

                    b.Property<string>("Ssid")
                        .HasColumnType("text");

                    b.Property<string>("TokenAuthSupport")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Udn")
                        .HasColumnType("text");

                    b.Property<string>("VoiceSupport")
                        .HasColumnType("text");

                    b.Property<string>("WallScreenRatio")
                        .HasColumnType("text");

                    b.Property<string>("WallService")
                        .HasColumnType("text");

                    b.Property<string>("WifiMac")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SamsungAdditionalDeviceInfo");
                });

            modelBuilder.Entity("TvServer.Models.Samsung.HardwareModels.SamsungTvInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("IsSupport")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Remote")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("SamsungTvInfo");
                });

            modelBuilder.Entity("TvServer.Models.Samsung.SavedSamsungDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DeviceInfoId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastKnownIp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Token")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceInfoId");

                    b.ToTable("SamsungDevices");
                });

            modelBuilder.Entity("TvServer.Models.Roku.HardwareModels.RokuApp", b =>
                {
                    b.HasOne("TvServer.Models.Roku.HardwareModels.RokuApps", null)
                        .WithMany("AppList")
                        .HasForeignKey("RokuAppsId");
                });

            modelBuilder.Entity("TvServer.Models.Roku.SavedRokuDeviceEntity", b =>
                {
                    b.HasOne("TvServer.Models.Roku.HardwareModels.RokuDeviceInfo", "DeviceInfo")
                        .WithMany()
                        .HasForeignKey("DeviceInfoId");

                    b.HasOne("TvServer.Models.Roku.HardwareModels.RokuApps", "RokuApps")
                        .WithMany()
                        .HasForeignKey("RokuAppsId");

                    b.Navigation("DeviceInfo");

                    b.Navigation("RokuApps");
                });

            modelBuilder.Entity("TvServer.Models.Samsung.Events.SamsungAppData", b =>
                {
                    b.HasOne("TvServer.Models.Samsung.SavedSamsungDeviceEntity", null)
                        .WithMany("SamsungApps")
                        .HasForeignKey("SavedSamsungDeviceEntityId");
                });

            modelBuilder.Entity("TvServer.Models.Samsung.HardwareModels.SamsungTvInfo", b =>
                {
                    b.HasOne("TvServer.Models.Samsung.HardwareModels.SamsungAdditionalDeviceInfo", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("TvServer.Models.Samsung.SavedSamsungDeviceEntity", b =>
                {
                    b.HasOne("TvServer.Models.Samsung.HardwareModels.SamsungTvInfo", "DeviceInfo")
                        .WithMany()
                        .HasForeignKey("DeviceInfoId");

                    b.Navigation("DeviceInfo");
                });

            modelBuilder.Entity("TvServer.Models.Roku.HardwareModels.RokuApps", b =>
                {
                    b.Navigation("AppList");
                });

            modelBuilder.Entity("TvServer.Models.Samsung.SavedSamsungDeviceEntity", b =>
                {
                    b.Navigation("SamsungApps");
                });
#pragma warning restore 612, 618
        }
    }
}
