// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TvServer.Models;

#nullable disable

namespace TvServerV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250804030334_addsamsungdata")]
    partial class addsamsungdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TvServerV2.Models.Roku.RokuApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RokuAppsId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RokuAppsId");

                    b.ToTable("RokuApp");
                });

            modelBuilder.Entity("TvServerV2.Models.Roku.RokuApps", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RokuApps");
                });

            modelBuilder.Entity("TvServerV2.Models.Roku.SavedRokuDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastKnownIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RokuAppsId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RokuAppsId");

                    b.ToTable("RokuDevices");
                });

            modelBuilder.Entity("TvServerV2.Models.Samsung.Events.SamsungAppData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AppType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsLock")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SavedSamsungDeviceEntityId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SavedSamsungDeviceEntityId");

                    b.ToTable("SamsungAppData");
                });

            modelBuilder.Entity("TvServerV2.Models.Samsung.SavedSamsungDeviceEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastKnownIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SamsungDevices");
                });

            modelBuilder.Entity("TvServerV2.Models.Roku.RokuApp", b =>
                {
                    b.HasOne("TvServerV2.Models.Roku.RokuApps", null)
                        .WithMany("AppList")
                        .HasForeignKey("RokuAppsId");
                });

            modelBuilder.Entity("TvServerV2.Models.Roku.SavedRokuDeviceEntity", b =>
                {
                    b.HasOne("TvServerV2.Models.Roku.RokuApps", "RokuApps")
                        .WithMany()
                        .HasForeignKey("RokuAppsId");

                    b.Navigation("RokuApps");
                });

            modelBuilder.Entity("TvServerV2.Models.Samsung.Events.SamsungAppData", b =>
                {
                    b.HasOne("TvServerV2.Models.Samsung.SavedSamsungDeviceEntity", null)
                        .WithMany("SamsungApps")
                        .HasForeignKey("SavedSamsungDeviceEntityId");
                });

            modelBuilder.Entity("TvServerV2.Models.Roku.RokuApps", b =>
                {
                    b.Navigation("AppList");
                });

            modelBuilder.Entity("TvServerV2.Models.Samsung.SavedSamsungDeviceEntity", b =>
                {
                    b.Navigation("SamsungApps");
                });
#pragma warning restore 612, 618
        }
    }
}
