//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class TvControlClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    apiBroadcast(): Promise<string> {
        let url_ = this.baseUrl + "/api/broadcast";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "plain/text"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiBroadcast(_response);
        });
    }

    protected processApiBroadcast(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;

                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    apiRokuDevicesGet(): Promise<RokuTvDto[]> {
        let url_ = this.baseUrl + "/api/roku/devices";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiRokuDevicesGet(_response);
        });
    }

    protected processApiRokuDevicesGet(response: Response): Promise<RokuTvDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                if (Array.isArray(resultData200)) {
                    result200 = [] as any;
                    for (let item of resultData200)
                        result200!.push(RokuTvDto.fromJS(item));
                }
                else {
                    result200 = null as any;
                }
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RokuTvDto[]>(null as any);
    }

    /**
     * @return OK
     */
    apiRokuDevicesDelete(id: string): Promise<string> {
        let url_ = this.baseUrl + "/api/roku/devices?";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined and cannot be null.");
        else
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "plain/text"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiRokuDevicesDelete(_response);
        });
    }

    protected processApiRokuDevicesDelete(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;

                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    apiRokuDevicesInfo(body: RokuDeviceRequest): Promise<RokuTvDto> {
        let url_ = this.baseUrl + "/api/roku/devices/info";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiRokuDevicesInfo(_response);
        });
    }

    protected processApiRokuDevicesInfo(response: Response): Promise<RokuTvDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = RokuTvDto.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RokuTvDto>(null as any);
    }

    /**
     * @return OK
     */
    apiRokuDevicesApps(body: RokuDeviceRequest): Promise<RokuApps> {
        let url_ = this.baseUrl + "/api/roku/devices/apps";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiRokuDevicesApps(_response);
        });
    }

    protected processApiRokuDevicesApps(response: Response): Promise<RokuApps> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = RokuApps.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<RokuApps>(null as any);
    }

    /**
     * @return OK
     */
    apiRokuDevicesKeyPress(body: RokuKeypressRequest): Promise<boolean> {
        let url_ = this.baseUrl + "/api/roku/devices/keyPress";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "plain/text"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiRokuDevicesKeyPress(_response);
        });
    }

    protected processApiRokuDevicesKeyPress(response: Response): Promise<boolean> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;

                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<boolean>(null as any);
    }

    /**
     * @return OK
     */
    apiRokuDevicesAppsIcon(body: RokuIconRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/roku/devices/apps/icon";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiRokuDevicesAppsIcon(_response);
        });
    }

    protected processApiRokuDevicesAppsIcon(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    apiSamsungDevicesGet(): Promise<SamsungTvDto[]> {
        let url_ = this.baseUrl + "/api/samsung/devices";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiSamsungDevicesGet(_response);
        });
    }

    protected processApiSamsungDevicesGet(response: Response): Promise<SamsungTvDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                if (Array.isArray(resultData200)) {
                    result200 = [] as any;
                    for (let item of resultData200)
                        result200!.push(SamsungTvDto.fromJS(item));
                }
                else {
                    result200 = null as any;
                }
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SamsungTvDto[]>(null as any);
    }

    /**
     * @return OK
     */
    apiSamsungDevicesDelete(id: string): Promise<boolean> {
        let url_ = this.baseUrl + "/api/samsung/devices?";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined and cannot be null.");
        else
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "plain/text"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiSamsungDevicesDelete(_response);
        });
    }

    protected processApiSamsungDevicesDelete(response: Response): Promise<boolean> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;

                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<boolean>(null as any);
    }

    /**
     * @return OK
     */
    apiSamsungDevicesInfo(body: SamsungDeviceRequest): Promise<SamsungTvDto> {
        let url_ = this.baseUrl + "/api/samsung/devices/info";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiSamsungDevicesInfo(_response);
        });
    }

    protected processApiSamsungDevicesInfo(response: Response): Promise<SamsungTvDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = SamsungTvDto.fromJS(resultData200);
                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SamsungTvDto>(null as any);
    }

    /**
     * @return OK
     */
    apiSamsungDevicesKeyPress(body: SamsungKeypressRequest): Promise<boolean> {
        let url_ = this.baseUrl + "/api/samsung/devices/keyPress";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "plain/text"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiSamsungDevicesKeyPress(_response);
        });
    }

    protected processApiSamsungDevicesKeyPress(response: Response): Promise<boolean> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;

                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<boolean>(null as any);
    }

    /**
     * @return OK
     */
    apiSamsungDevicesLaunchApp(body: SamsungLaunchAppRequest): Promise<boolean> {
        let url_ = this.baseUrl + "/api/samsung/devices/launchApp";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "plain/text"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiSamsungDevicesLaunchApp(_response);
        });
    }

    protected processApiSamsungDevicesLaunchApp(response: Response): Promise<boolean> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;

                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<boolean>(null as any);
    }

    /**
     * @return OK
     */
    apiSamsungDevicesApps(deviceId: string): Promise<boolean> {
        let url_ = this.baseUrl + "/api/samsung/devices/apps?";
        if (deviceId === undefined || deviceId === null)
            throw new globalThis.Error("The parameter 'deviceId' must be defined and cannot be null.");
        else
            url_ += "deviceId=" + encodeURIComponent("" + deviceId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "plain/text"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processApiSamsungDevicesApps(_response);
        });
    }

    protected processApiSamsungDevicesApps(response: Response): Promise<boolean> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : null as any;

                return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<boolean>(null as any);
    }
}

export enum DeviceStatus {
    _0 = 0,
    _1 = 1,
    _2 = 2,
}

export class RokuApp implements IRokuApp {
    id?: string | undefined;
    type?: string | undefined;
    version?: string | undefined;
    name?: string | undefined;

    constructor(data?: IRokuApp) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.type = _data["type"];
            this.version = _data["version"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): RokuApp {
        data = typeof data === 'object' ? data : {};
        let result = new RokuApp();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["type"] = this.type;
        data["version"] = this.version;
        data["name"] = this.name;
        return data;
    }
}

export interface IRokuApp {
    id?: string | undefined;
    type?: string | undefined;
    version?: string | undefined;
    name?: string | undefined;
}

export class RokuApps implements IRokuApps {
    id?: string | undefined;
    appList?: RokuApp[] | undefined;

    constructor(data?: IRokuApps) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            if (Array.isArray(_data["appList"])) {
                this.appList = [] as any;
                for (let item of _data["appList"])
                    this.appList!.push(RokuApp.fromJS(item));
            }
        }
    }

    static fromJS(data: any): RokuApps {
        data = typeof data === 'object' ? data : {};
        let result = new RokuApps();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        if (Array.isArray(this.appList)) {
            data["appList"] = [];
            for (let item of this.appList)
                data["appList"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IRokuApps {
    id?: string | undefined;
    appList?: RokuApp[] | undefined;
}

export class RokuDeviceInfo implements IRokuDeviceInfo {
    udn?: string | undefined;
    serialNumber?: string | undefined;
    deviceId?: string | undefined;
    advertisingId?: string | undefined;
    vendorName?: string | undefined;
    modelName?: string | undefined;
    modelNumber?: string | undefined;
    modelRegion?: string | undefined;
    isTv?: boolean;
    isStick?: boolean;
    screenSize?: number;
    panelId?: number;
    mobileHasLiveTv?: boolean;
    uiResolution?: string | undefined;
    tunerType?: string | undefined;
    supportsEthernet?: boolean;
    wifiMac?: string | undefined;
    wifiDriver?: string | undefined;
    hasWifi5GSupport?: boolean;
    ethernetMac?: string | undefined;
    networkType?: string | undefined;
    networkName?: string | undefined;
    friendlyDeviceName?: string | undefined;
    friendlyModelName?: string | undefined;
    defaultDeviceName?: string | undefined;
    userDeviceName?: string | undefined;
    userDeviceLocation?: string | undefined;
    buildNumber?: string | undefined;
    softwareVersion?: string | undefined;
    softwareBuild?: string | undefined;
    lightningBaseBuildNumber?: string | undefined;
    uiBuildNumber?: string | undefined;
    uiSoftwareVersion?: string | undefined;
    uiSoftwareBuild?: string | undefined;
    secureDevice?: boolean;
    language?: string | undefined;
    country?: string | undefined;
    locale?: string | undefined;
    timeZoneAuto?: boolean;
    timeZone?: string | undefined;
    timeZoneName?: string | undefined;
    timeZoneTz?: string | undefined;
    timeZoneOffset?: number;
    clockFormat?: string | undefined;
    uptime?: number;
    powerMode?: string | undefined;
    supportsSuspend?: boolean;
    supportsFindRemote?: boolean;
    supportsAudioGuide?: boolean;
    supportsRva?: boolean;
    hasHandsFreeVoiceRemote?: boolean;
    developerEnabled?: boolean;
    keyedDeveloperId?: string | undefined;
    deviceAutomationBridgeEnabled?: boolean;
    searchEnabled?: boolean;
    searchChannelsEnabled?: boolean;
    voiceSearchEnabled?: boolean;
    supportsPrivateListening?: boolean;
    supportsPrivateListeningDtv?: boolean;
    supportsWarmStandby?: boolean;
    headphonesConnected?: boolean;
    supportsAudioSettings?: boolean;
    expertPqEnabled?: number;
    supportsEcsTextedit?: boolean;
    supportsEcsMicrophone?: boolean;
    supportsWakeOnWlan?: boolean;
    supportsAirplay?: boolean;
    hasPlayOnRoku?: boolean;
    hasMobileScreensaver?: boolean;
    supportUrl?: string | undefined;
    grandcentralVersion?: string | undefined;
    supportsTrc?: boolean;
    trcVersion?: string | undefined;
    trcChannelVersion?: string | undefined;
    avSyncCalibrationEnabled?: string | undefined;

    constructor(data?: IRokuDeviceInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.udn = _data["udn"];
            this.serialNumber = _data["serialNumber"];
            this.deviceId = _data["deviceId"];
            this.advertisingId = _data["advertisingId"];
            this.vendorName = _data["vendorName"];
            this.modelName = _data["modelName"];
            this.modelNumber = _data["modelNumber"];
            this.modelRegion = _data["modelRegion"];
            this.isTv = _data["isTv"];
            this.isStick = _data["isStick"];
            this.screenSize = _data["screenSize"];
            this.panelId = _data["panelId"];
            this.mobileHasLiveTv = _data["mobileHasLiveTv"];
            this.uiResolution = _data["uiResolution"];
            this.tunerType = _data["tunerType"];
            this.supportsEthernet = _data["supportsEthernet"];
            this.wifiMac = _data["wifiMac"];
            this.wifiDriver = _data["wifiDriver"];
            this.hasWifi5GSupport = _data["hasWifi5GSupport"];
            this.ethernetMac = _data["ethernetMac"];
            this.networkType = _data["networkType"];
            this.networkName = _data["networkName"];
            this.friendlyDeviceName = _data["friendlyDeviceName"];
            this.friendlyModelName = _data["friendlyModelName"];
            this.defaultDeviceName = _data["defaultDeviceName"];
            this.userDeviceName = _data["userDeviceName"];
            this.userDeviceLocation = _data["userDeviceLocation"];
            this.buildNumber = _data["buildNumber"];
            this.softwareVersion = _data["softwareVersion"];
            this.softwareBuild = _data["softwareBuild"];
            this.lightningBaseBuildNumber = _data["lightningBaseBuildNumber"];
            this.uiBuildNumber = _data["uiBuildNumber"];
            this.uiSoftwareVersion = _data["uiSoftwareVersion"];
            this.uiSoftwareBuild = _data["uiSoftwareBuild"];
            this.secureDevice = _data["secureDevice"];
            this.language = _data["language"];
            this.country = _data["country"];
            this.locale = _data["locale"];
            this.timeZoneAuto = _data["timeZoneAuto"];
            this.timeZone = _data["timeZone"];
            this.timeZoneName = _data["timeZoneName"];
            this.timeZoneTz = _data["timeZoneTz"];
            this.timeZoneOffset = _data["timeZoneOffset"];
            this.clockFormat = _data["clockFormat"];
            this.uptime = _data["uptime"];
            this.powerMode = _data["powerMode"];
            this.supportsSuspend = _data["supportsSuspend"];
            this.supportsFindRemote = _data["supportsFindRemote"];
            this.supportsAudioGuide = _data["supportsAudioGuide"];
            this.supportsRva = _data["supportsRva"];
            this.hasHandsFreeVoiceRemote = _data["hasHandsFreeVoiceRemote"];
            this.developerEnabled = _data["developerEnabled"];
            this.keyedDeveloperId = _data["keyedDeveloperId"];
            this.deviceAutomationBridgeEnabled = _data["deviceAutomationBridgeEnabled"];
            this.searchEnabled = _data["searchEnabled"];
            this.searchChannelsEnabled = _data["searchChannelsEnabled"];
            this.voiceSearchEnabled = _data["voiceSearchEnabled"];
            this.supportsPrivateListening = _data["supportsPrivateListening"];
            this.supportsPrivateListeningDtv = _data["supportsPrivateListeningDtv"];
            this.supportsWarmStandby = _data["supportsWarmStandby"];
            this.headphonesConnected = _data["headphonesConnected"];
            this.supportsAudioSettings = _data["supportsAudioSettings"];
            this.expertPqEnabled = _data["expertPqEnabled"];
            this.supportsEcsTextedit = _data["supportsEcsTextedit"];
            this.supportsEcsMicrophone = _data["supportsEcsMicrophone"];
            this.supportsWakeOnWlan = _data["supportsWakeOnWlan"];
            this.supportsAirplay = _data["supportsAirplay"];
            this.hasPlayOnRoku = _data["hasPlayOnRoku"];
            this.hasMobileScreensaver = _data["hasMobileScreensaver"];
            this.supportUrl = _data["supportUrl"];
            this.grandcentralVersion = _data["grandcentralVersion"];
            this.supportsTrc = _data["supportsTrc"];
            this.trcVersion = _data["trcVersion"];
            this.trcChannelVersion = _data["trcChannelVersion"];
            this.avSyncCalibrationEnabled = _data["avSyncCalibrationEnabled"];
        }
    }

    static fromJS(data: any): RokuDeviceInfo {
        data = typeof data === 'object' ? data : {};
        let result = new RokuDeviceInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["udn"] = this.udn;
        data["serialNumber"] = this.serialNumber;
        data["deviceId"] = this.deviceId;
        data["advertisingId"] = this.advertisingId;
        data["vendorName"] = this.vendorName;
        data["modelName"] = this.modelName;
        data["modelNumber"] = this.modelNumber;
        data["modelRegion"] = this.modelRegion;
        data["isTv"] = this.isTv;
        data["isStick"] = this.isStick;
        data["screenSize"] = this.screenSize;
        data["panelId"] = this.panelId;
        data["mobileHasLiveTv"] = this.mobileHasLiveTv;
        data["uiResolution"] = this.uiResolution;
        data["tunerType"] = this.tunerType;
        data["supportsEthernet"] = this.supportsEthernet;
        data["wifiMac"] = this.wifiMac;
        data["wifiDriver"] = this.wifiDriver;
        data["hasWifi5GSupport"] = this.hasWifi5GSupport;
        data["ethernetMac"] = this.ethernetMac;
        data["networkType"] = this.networkType;
        data["networkName"] = this.networkName;
        data["friendlyDeviceName"] = this.friendlyDeviceName;
        data["friendlyModelName"] = this.friendlyModelName;
        data["defaultDeviceName"] = this.defaultDeviceName;
        data["userDeviceName"] = this.userDeviceName;
        data["userDeviceLocation"] = this.userDeviceLocation;
        data["buildNumber"] = this.buildNumber;
        data["softwareVersion"] = this.softwareVersion;
        data["softwareBuild"] = this.softwareBuild;
        data["lightningBaseBuildNumber"] = this.lightningBaseBuildNumber;
        data["uiBuildNumber"] = this.uiBuildNumber;
        data["uiSoftwareVersion"] = this.uiSoftwareVersion;
        data["uiSoftwareBuild"] = this.uiSoftwareBuild;
        data["secureDevice"] = this.secureDevice;
        data["language"] = this.language;
        data["country"] = this.country;
        data["locale"] = this.locale;
        data["timeZoneAuto"] = this.timeZoneAuto;
        data["timeZone"] = this.timeZone;
        data["timeZoneName"] = this.timeZoneName;
        data["timeZoneTz"] = this.timeZoneTz;
        data["timeZoneOffset"] = this.timeZoneOffset;
        data["clockFormat"] = this.clockFormat;
        data["uptime"] = this.uptime;
        data["powerMode"] = this.powerMode;
        data["supportsSuspend"] = this.supportsSuspend;
        data["supportsFindRemote"] = this.supportsFindRemote;
        data["supportsAudioGuide"] = this.supportsAudioGuide;
        data["supportsRva"] = this.supportsRva;
        data["hasHandsFreeVoiceRemote"] = this.hasHandsFreeVoiceRemote;
        data["developerEnabled"] = this.developerEnabled;
        data["keyedDeveloperId"] = this.keyedDeveloperId;
        data["deviceAutomationBridgeEnabled"] = this.deviceAutomationBridgeEnabled;
        data["searchEnabled"] = this.searchEnabled;
        data["searchChannelsEnabled"] = this.searchChannelsEnabled;
        data["voiceSearchEnabled"] = this.voiceSearchEnabled;
        data["supportsPrivateListening"] = this.supportsPrivateListening;
        data["supportsPrivateListeningDtv"] = this.supportsPrivateListeningDtv;
        data["supportsWarmStandby"] = this.supportsWarmStandby;
        data["headphonesConnected"] = this.headphonesConnected;
        data["supportsAudioSettings"] = this.supportsAudioSettings;
        data["expertPqEnabled"] = this.expertPqEnabled;
        data["supportsEcsTextedit"] = this.supportsEcsTextedit;
        data["supportsEcsMicrophone"] = this.supportsEcsMicrophone;
        data["supportsWakeOnWlan"] = this.supportsWakeOnWlan;
        data["supportsAirplay"] = this.supportsAirplay;
        data["hasPlayOnRoku"] = this.hasPlayOnRoku;
        data["hasMobileScreensaver"] = this.hasMobileScreensaver;
        data["supportUrl"] = this.supportUrl;
        data["grandcentralVersion"] = this.grandcentralVersion;
        data["supportsTrc"] = this.supportsTrc;
        data["trcVersion"] = this.trcVersion;
        data["trcChannelVersion"] = this.trcChannelVersion;
        data["avSyncCalibrationEnabled"] = this.avSyncCalibrationEnabled;
        return data;
    }
}

export interface IRokuDeviceInfo {
    udn?: string | undefined;
    serialNumber?: string | undefined;
    deviceId?: string | undefined;
    advertisingId?: string | undefined;
    vendorName?: string | undefined;
    modelName?: string | undefined;
    modelNumber?: string | undefined;
    modelRegion?: string | undefined;
    isTv?: boolean;
    isStick?: boolean;
    screenSize?: number;
    panelId?: number;
    mobileHasLiveTv?: boolean;
    uiResolution?: string | undefined;
    tunerType?: string | undefined;
    supportsEthernet?: boolean;
    wifiMac?: string | undefined;
    wifiDriver?: string | undefined;
    hasWifi5GSupport?: boolean;
    ethernetMac?: string | undefined;
    networkType?: string | undefined;
    networkName?: string | undefined;
    friendlyDeviceName?: string | undefined;
    friendlyModelName?: string | undefined;
    defaultDeviceName?: string | undefined;
    userDeviceName?: string | undefined;
    userDeviceLocation?: string | undefined;
    buildNumber?: string | undefined;
    softwareVersion?: string | undefined;
    softwareBuild?: string | undefined;
    lightningBaseBuildNumber?: string | undefined;
    uiBuildNumber?: string | undefined;
    uiSoftwareVersion?: string | undefined;
    uiSoftwareBuild?: string | undefined;
    secureDevice?: boolean;
    language?: string | undefined;
    country?: string | undefined;
    locale?: string | undefined;
    timeZoneAuto?: boolean;
    timeZone?: string | undefined;
    timeZoneName?: string | undefined;
    timeZoneTz?: string | undefined;
    timeZoneOffset?: number;
    clockFormat?: string | undefined;
    uptime?: number;
    powerMode?: string | undefined;
    supportsSuspend?: boolean;
    supportsFindRemote?: boolean;
    supportsAudioGuide?: boolean;
    supportsRva?: boolean;
    hasHandsFreeVoiceRemote?: boolean;
    developerEnabled?: boolean;
    keyedDeveloperId?: string | undefined;
    deviceAutomationBridgeEnabled?: boolean;
    searchEnabled?: boolean;
    searchChannelsEnabled?: boolean;
    voiceSearchEnabled?: boolean;
    supportsPrivateListening?: boolean;
    supportsPrivateListeningDtv?: boolean;
    supportsWarmStandby?: boolean;
    headphonesConnected?: boolean;
    supportsAudioSettings?: boolean;
    expertPqEnabled?: number;
    supportsEcsTextedit?: boolean;
    supportsEcsMicrophone?: boolean;
    supportsWakeOnWlan?: boolean;
    supportsAirplay?: boolean;
    hasPlayOnRoku?: boolean;
    hasMobileScreensaver?: boolean;
    supportUrl?: string | undefined;
    grandcentralVersion?: string | undefined;
    supportsTrc?: boolean;
    trcVersion?: string | undefined;
    trcChannelVersion?: string | undefined;
    avSyncCalibrationEnabled?: string | undefined;
}

export class RokuDeviceRequest implements IRokuDeviceRequest {
    deviceId?: string | undefined;

    constructor(data?: IRokuDeviceRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.deviceId = _data["deviceId"];
        }
    }

    static fromJS(data: any): RokuDeviceRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RokuDeviceRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["deviceId"] = this.deviceId;
        return data;
    }
}

export interface IRokuDeviceRequest {
    deviceId?: string | undefined;
}

export class RokuIconRequest implements IRokuIconRequest {
    deviceId?: string | undefined;
    appId?: string | undefined;

    constructor(data?: IRokuIconRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.deviceId = _data["deviceId"];
            this.appId = _data["appId"];
        }
    }

    static fromJS(data: any): RokuIconRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RokuIconRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["deviceId"] = this.deviceId;
        data["appId"] = this.appId;
        return data;
    }
}

export interface IRokuIconRequest {
    deviceId?: string | undefined;
    appId?: string | undefined;
}

export enum RokuKeypress {
    Home = "Home",
    Back = "Back",
    Select = "Select",
    Left = "Left",
    Right = "Right",
    Down = "Down",
    Up = "Up",
    Play = "Play",
    Pause = "Pause",
    PlayPause = "PlayPause",
    Stop = "Stop",
    Rewind = "Rewind",
    FastForward = "FastForward",
    VolumeUp = "VolumeUp",
    VolumeDown = "VolumeDown",
    VolumeMute = "VolumeMute",
    PowerOn = "PowerOn",
    PowerOff = "PowerOff",
    InputTuner = "InputTuner",
    InputHDMI1 = "InputHDMI1",
    InputHDMI2 = "InputHDMI2",
    InputHDMI3 = "InputHDMI3",
    InputHDMI4 = "InputHDMI4",
    InputAV = "InputAV",
    InstantReplay = "InstantReplay",
    Info = "Info",
    Lit = "Lit",
    Enter = "Enter",
    Search = "Search",
    FindRemote = "FindRemote",
    Launch = "Launch",
    Backspace = "Backspace",
    Clear = "Clear",
    Options = "Options",
    Exit = "Exit",
}

export class RokuKeypressRequest implements IRokuKeypressRequest {
    deviceId?: string | undefined;
    keypress?: RokuKeypress;
    additionalData?: string | undefined;

    constructor(data?: IRokuKeypressRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.deviceId = _data["deviceId"];
            this.keypress = _data["keypress"];
            this.additionalData = _data["additionalData"];
        }
    }

    static fromJS(data: any): RokuKeypressRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RokuKeypressRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["deviceId"] = this.deviceId;
        data["keypress"] = this.keypress;
        data["additionalData"] = this.additionalData;
        return data;
    }
}

export interface IRokuKeypressRequest {
    deviceId?: string | undefined;
    keypress?: RokuKeypress;
    additionalData?: string | undefined;
}

export class RokuTvDto implements IRokuTvDto {
    id!: string;
    deviceName!: string;
    lastKnownIp?: string | undefined;
    status?: DeviceStatus;
    rokuApps?: RokuApps;
    rokuDeviceInfo?: RokuDeviceInfo;

    constructor(data?: IRokuTvDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.deviceName = _data["deviceName"];
            this.lastKnownIp = _data["lastKnownIp"];
            this.status = _data["status"];
            this.rokuApps = _data["rokuApps"] ? RokuApps.fromJS(_data["rokuApps"]) : undefined as any;
            this.rokuDeviceInfo = _data["rokuDeviceInfo"] ? RokuDeviceInfo.fromJS(_data["rokuDeviceInfo"]) : undefined as any;
        }
    }

    static fromJS(data: any): RokuTvDto {
        data = typeof data === 'object' ? data : {};
        let result = new RokuTvDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["deviceName"] = this.deviceName;
        data["lastKnownIp"] = this.lastKnownIp;
        data["status"] = this.status;
        data["rokuApps"] = this.rokuApps ? this.rokuApps.toJSON() : undefined as any;
        data["rokuDeviceInfo"] = this.rokuDeviceInfo ? this.rokuDeviceInfo.toJSON() : undefined as any;
        return data;
    }
}

export interface IRokuTvDto {
    id: string;
    deviceName: string;
    lastKnownIp?: string | undefined;
    status?: DeviceStatus;
    rokuApps?: RokuApps;
    rokuDeviceInfo?: RokuDeviceInfo;
}

export class SamsungAdditionalDeviceInfo implements ISamsungAdditionalDeviceInfo {
    frameTVSupport?: string | undefined;
    gamePadSupport?: string | undefined;
    imeSyncedSupport?: string | undefined;
    language?: string | undefined;
    os?: string | undefined;
    powerState?: string | undefined;
    tokenAuthSupport?: string | undefined;
    voiceSupport?: string | undefined;
    wallScreenRatio?: string | undefined;
    wallService?: string | undefined;
    countryCode?: string | undefined;
    description?: string | undefined;
    developerIP?: string | undefined;
    developerMode?: string | undefined;
    duid?: string | undefined;
    firmwareVersion?: string | undefined;
    id?: string | undefined;
    ip?: string | undefined;
    model?: string | undefined;
    modelName?: string | undefined;
    name?: string | undefined;
    networkType?: string | undefined;
    resolution?: string | undefined;
    smartHubAgreement?: string | undefined;
    ssid?: string | undefined;
    type?: string | undefined;
    udn?: string | undefined;
    wifiMac?: string | undefined;

    constructor(data?: ISamsungAdditionalDeviceInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.frameTVSupport = _data["frameTVSupport"];
            this.gamePadSupport = _data["gamePadSupport"];
            this.imeSyncedSupport = _data["imeSyncedSupport"];
            this.language = _data["language"];
            this.os = _data["os"];
            this.powerState = _data["powerState"];
            this.tokenAuthSupport = _data["tokenAuthSupport"];
            this.voiceSupport = _data["voiceSupport"];
            this.wallScreenRatio = _data["wallScreenRatio"];
            this.wallService = _data["wallService"];
            this.countryCode = _data["countryCode"];
            this.description = _data["description"];
            this.developerIP = _data["developerIP"];
            this.developerMode = _data["developerMode"];
            this.duid = _data["duid"];
            this.firmwareVersion = _data["firmwareVersion"];
            this.id = _data["id"];
            this.ip = _data["ip"];
            this.model = _data["model"];
            this.modelName = _data["modelName"];
            this.name = _data["name"];
            this.networkType = _data["networkType"];
            this.resolution = _data["resolution"];
            this.smartHubAgreement = _data["smartHubAgreement"];
            this.ssid = _data["ssid"];
            this.type = _data["type"];
            this.udn = _data["udn"];
            this.wifiMac = _data["wifiMac"];
        }
    }

    static fromJS(data: any): SamsungAdditionalDeviceInfo {
        data = typeof data === 'object' ? data : {};
        let result = new SamsungAdditionalDeviceInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["frameTVSupport"] = this.frameTVSupport;
        data["gamePadSupport"] = this.gamePadSupport;
        data["imeSyncedSupport"] = this.imeSyncedSupport;
        data["language"] = this.language;
        data["os"] = this.os;
        data["powerState"] = this.powerState;
        data["tokenAuthSupport"] = this.tokenAuthSupport;
        data["voiceSupport"] = this.voiceSupport;
        data["wallScreenRatio"] = this.wallScreenRatio;
        data["wallService"] = this.wallService;
        data["countryCode"] = this.countryCode;
        data["description"] = this.description;
        data["developerIP"] = this.developerIP;
        data["developerMode"] = this.developerMode;
        data["duid"] = this.duid;
        data["firmwareVersion"] = this.firmwareVersion;
        data["id"] = this.id;
        data["ip"] = this.ip;
        data["model"] = this.model;
        data["modelName"] = this.modelName;
        data["name"] = this.name;
        data["networkType"] = this.networkType;
        data["resolution"] = this.resolution;
        data["smartHubAgreement"] = this.smartHubAgreement;
        data["ssid"] = this.ssid;
        data["type"] = this.type;
        data["udn"] = this.udn;
        data["wifiMac"] = this.wifiMac;
        return data;
    }
}

export interface ISamsungAdditionalDeviceInfo {
    frameTVSupport?: string | undefined;
    gamePadSupport?: string | undefined;
    imeSyncedSupport?: string | undefined;
    language?: string | undefined;
    os?: string | undefined;
    powerState?: string | undefined;
    tokenAuthSupport?: string | undefined;
    voiceSupport?: string | undefined;
    wallScreenRatio?: string | undefined;
    wallService?: string | undefined;
    countryCode?: string | undefined;
    description?: string | undefined;
    developerIP?: string | undefined;
    developerMode?: string | undefined;
    duid?: string | undefined;
    firmwareVersion?: string | undefined;
    id?: string | undefined;
    ip?: string | undefined;
    model?: string | undefined;
    modelName?: string | undefined;
    name?: string | undefined;
    networkType?: string | undefined;
    resolution?: string | undefined;
    smartHubAgreement?: string | undefined;
    ssid?: string | undefined;
    type?: string | undefined;
    udn?: string | undefined;
    wifiMac?: string | undefined;
}

export class SamsungAppData implements ISamsungAppData {
    id?: string | undefined;
    appId?: string | undefined;
    appType?: number;
    icon?: string | undefined;
    isLock?: number;
    name?: string | undefined;

    constructor(data?: ISamsungAppData) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.appId = _data["appId"];
            this.appType = _data["appType"];
            this.icon = _data["icon"];
            this.isLock = _data["isLock"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): SamsungAppData {
        data = typeof data === 'object' ? data : {};
        let result = new SamsungAppData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["appId"] = this.appId;
        data["appType"] = this.appType;
        data["icon"] = this.icon;
        data["isLock"] = this.isLock;
        data["name"] = this.name;
        return data;
    }
}

export interface ISamsungAppData {
    id?: string | undefined;
    appId?: string | undefined;
    appType?: number;
    icon?: string | undefined;
    isLock?: number;
    name?: string | undefined;
}

export class SamsungDeviceRequest implements ISamsungDeviceRequest {
    deviceId?: string | undefined;

    constructor(data?: ISamsungDeviceRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.deviceId = _data["deviceId"];
        }
    }

    static fromJS(data: any): SamsungDeviceRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SamsungDeviceRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["deviceId"] = this.deviceId;
        return data;
    }
}

export interface ISamsungDeviceRequest {
    deviceId?: string | undefined;
}

export enum SamsungKeypress {
    KEY_POWER = "KEY_POWER",
    KEY_HOME = "KEY_HOME",
    KEY_SOURCE = "KEY_SOURCE",
    KEY_GUIDE = "KEY_GUIDE",
    KEY_TOOLS = "KEY_TOOLS",
    KEY_INFO = "KEY_INFO",
    KEY_UP = "KEY_UP",
    KEY_DOWN = "KEY_DOWN",
    KEY_LEFT = "KEY_LEFT",
    KEY_RIGHT = "KEY_RIGHT",
    KEY_ENTER = "KEY_ENTER",
    KEY_RETURN = "KEY_RETURN",
    KEY_CH_LIST = "KEY_CH_LIST",
    KEY_CHUP = "KEY_CHUP",
    KEY_CHDOWN = "KEY_CHDOWN",
    KEY_VOLUP = "KEY_VOLUP",
    KEY_VOLDOWN = "KEY_VOLDOWN",
    KEY_MUTE = "KEY_MUTE",
    KEY_EXIT = "KEY_EXIT",
    KEY_RED = "KEY_RED",
    KEY_GREEN = "KEY_GREEN",
    KEY_YELLOW = "KEY_YELLOW",
    KEY_BLUE = "KEY_BLUE",
    KEY_FACTORY = "KEY_FACTORY",
}

export class SamsungKeypressRequest implements ISamsungKeypressRequest {
    deviceId?: string | undefined;
    keypress?: SamsungKeypress;
    type?: SamsungKeypressType;

    constructor(data?: ISamsungKeypressRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.deviceId = _data["deviceId"];
            this.keypress = _data["keypress"];
            this.type = _data["type"];
        }
    }

    static fromJS(data: any): SamsungKeypressRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SamsungKeypressRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["deviceId"] = this.deviceId;
        data["keypress"] = this.keypress;
        data["type"] = this.type;
        return data;
    }
}

export interface ISamsungKeypressRequest {
    deviceId?: string | undefined;
    keypress?: SamsungKeypress;
    type?: SamsungKeypressType;
}

export enum SamsungKeypressType {
    Click = "Click",
    Press = "Press",
    Release = "Release",
}

export class SamsungLaunchAppRequest implements ISamsungLaunchAppRequest {
    deviceId?: string | undefined;
    appId?: string | undefined;

    constructor(data?: ISamsungLaunchAppRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.deviceId = _data["deviceId"];
            this.appId = _data["appId"];
        }
    }

    static fromJS(data: any): SamsungLaunchAppRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SamsungLaunchAppRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["deviceId"] = this.deviceId;
        data["appId"] = this.appId;
        return data;
    }
}

export interface ISamsungLaunchAppRequest {
    deviceId?: string | undefined;
    appId?: string | undefined;
}

export class SamsungTvDto implements ISamsungTvDto {
    id!: string;
    deviceName!: string;
    lastKnownIp?: string | undefined;
    status?: DeviceStatus;
    samsungApps?: SamsungAppData[] | undefined;
    deviceInfo?: SamsungTvInfo;

    constructor(data?: ISamsungTvDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.deviceName = _data["deviceName"];
            this.lastKnownIp = _data["lastKnownIp"];
            this.status = _data["status"];
            if (Array.isArray(_data["samsungApps"])) {
                this.samsungApps = [] as any;
                for (let item of _data["samsungApps"])
                    this.samsungApps!.push(SamsungAppData.fromJS(item));
            }
            this.deviceInfo = _data["deviceInfo"] ? SamsungTvInfo.fromJS(_data["deviceInfo"]) : undefined as any;
        }
    }

    static fromJS(data: any): SamsungTvDto {
        data = typeof data === 'object' ? data : {};
        let result = new SamsungTvDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["deviceName"] = this.deviceName;
        data["lastKnownIp"] = this.lastKnownIp;
        data["status"] = this.status;
        if (Array.isArray(this.samsungApps)) {
            data["samsungApps"] = [];
            for (let item of this.samsungApps)
                data["samsungApps"].push(item ? item.toJSON() : undefined as any);
        }
        data["deviceInfo"] = this.deviceInfo ? this.deviceInfo.toJSON() : undefined as any;
        return data;
    }
}

export interface ISamsungTvDto {
    id: string;
    deviceName: string;
    lastKnownIp?: string | undefined;
    status?: DeviceStatus;
    samsungApps?: SamsungAppData[] | undefined;
    deviceInfo?: SamsungTvInfo;
}

export class SamsungTvInfo implements ISamsungTvInfo {
    device?: SamsungAdditionalDeviceInfo;
    id?: string | undefined;
    isSupport?: string | undefined;
    name?: string | undefined;
    remote?: string | undefined;
    type?: string | undefined;
    uri?: string | undefined;
    version?: string | undefined;

    constructor(data?: ISamsungTvInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.device = _data["device"] ? SamsungAdditionalDeviceInfo.fromJS(_data["device"]) : undefined as any;
            this.id = _data["id"];
            this.isSupport = _data["isSupport"];
            this.name = _data["name"];
            this.remote = _data["remote"];
            this.type = _data["type"];
            this.uri = _data["uri"];
            this.version = _data["version"];
        }
    }

    static fromJS(data: any): SamsungTvInfo {
        data = typeof data === 'object' ? data : {};
        let result = new SamsungTvInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["device"] = this.device ? this.device.toJSON() : undefined as any;
        data["id"] = this.id;
        data["isSupport"] = this.isSupport;
        data["name"] = this.name;
        data["remote"] = this.remote;
        data["type"] = this.type;
        data["uri"] = this.uri;
        data["version"] = this.version;
        return data;
    }
}

export interface ISamsungTvInfo {
    device?: SamsungAdditionalDeviceInfo;
    id?: string | undefined;
    isSupport?: string | undefined;
    name?: string | undefined;
    remote?: string | undefined;
    type?: string | undefined;
    uri?: string | undefined;
    version?: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}